### ISSUE TITLE
npm install fails because of failed shasum checking

### ISSUE THREAD

**Issue by yorkie** [browserstack/browserstack-runner#104]
```
npm WARN package.json duplo@1.7.1 No repository field.
npm ERR! Error: shasum check failed for /var/folders/gd/xzyzg3891lvgsgynzl72vlyc0000gn/T/npm-1106-xXXQklPd/registry.npmjs.org/browserstack-runner/-/browserstack-runner-0.2.2.tgz
npm ERR! Expected: 4a50ced875371dbd0906ffea60788abea4a2b5cf
npm ERR! Actual:   c84a458caca706d44407076c7ab5a3ef5cab6626
npm ERR! From:     https://registry.npmjs.org/browserstack-runner/-/browserstack-runner-0.2.2.tgz
npm ERR!     at /usr/local/lib/node_modules/npm/node_modules/sha/index.js:38:8
npm ERR!     at ReadStream.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/sha/index.js:85:7)
npm ERR!     at ReadStream.emit (events.js:117:20)
npm ERR!     at _stream_readable.js:943:16
npm ERR!     at process._tickCallback (node.js:419:13)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Darwin 14.0.0
npm ERR! command "node" "/usr/local/bin/npm" "install"
npm ERR! cwd /Users/yorkie/workspace/pixbi/duplo
npm ERR! node -v v0.10.32
npm ERR! npm -v 1.4.28
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/yorkie/workspace/pixbi/duplo/npm-debug.log
npm ERR! not ok code 0
```

as i known if the owner of this repo release with `--force`? suggest bump version to resolve this issue, thank you :-)

**Comment by 9ikhan** [comment]
@yorkie - we have release many versions since the issue was reported. Can you please check again ?

**Comment by yorkie** [comment]
0.3.5 is working :)
