### ISSUE TITLE
Persistent ETIMEDOUT error

### ISSUE THREAD

**Issue by jzaefferer** [browserstack/browserstack-runner#109]
This currently makes browserstack-runner completely unusable for me. The error is pretty useless:

```sh
~/dev/jquery-ui [git:optimize-testsuites?] $ browserstack-runner

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: connect ETIMEDOUT
    at errnoException (net.js:904:11)
    at Object.afterConnect [as oncomplete] (net.js:895:19)
```

To get some more output, I've installed the `long-stack-traces` module and required it in `cli.js`, then installed my local copy globally (`npm install -g .`). With that in place, I get a longer stacktrace:

```sh
~/dev/jquery-ui [git:optimize-testsuites?] $ browserstack-runner
Launching 2 worker(s) for 2 run(s).
Uncaught Error: connect ETIMEDOUT
    at errnoException (net.js:904:11)
    at Object.afterConnect [as oncomplete] (net.js:895:19)
----------------------------------------
    at EventEmitter.on
    at Socket.<anonymous> (_stream_readable.js:688:33)
    at http.js:1753:12
    at process._tickCallback (node.js:419:13)
----------------------------------------
    at process.nextTick
    at ClientRequest.onSocket (http.js:1730:11)
    at Agent.addRequest (http.js:1269:9)
    at new ClientRequest (http.js:1416:16)
    at Object.request (http.js:1843:10)
    at Version.request (/usr/local/lib/node_modules/browserstack-runner/node_modules/browserstack/lib/browserstack.js:163:18)
    at Version.getWorkers (/usr/local/lib/node_modules/browserstack-runner/node_modules/browserstack/lib/browserstack.js:95:8)
    at [object Object].<anonymous> (/usr/local/lib/node_modules/browserstack-runner/bin/cli.js:195:14)
----------------------------------------
    at Object.setInterval
    at Object.start (/usr/local/lib/node_modules/browserstack-runner/bin/cli.js:194:27)
    at /usr/local/lib/node_modules/browserstack-runner/bin/cli.js:278:22
    at [object Object].<anonymous> (/usr/local/lib/node_modules/browserstack-runner/lib/local.js:62:11)
    at Timer.listOnTimeout [as ontimeout] (timers.js:110:15)
----------------------------------------
    at Object.setTimeout
    at Socket.<anonymous> (/usr/local/lib/node_modules/browserstack-runner/lib/local.js:61:9)
    at Socket.emit (events.js:117:20)
    at Socket.<anonymous> (_stream_readable.js:745:14)
    at Socket.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:407:10)
    at emitReadable (_stream_readable.js:403:5)
----------------------------------------
    at EventEmitter.on
    at tunnelLauncher (/usr/local/lib/node_modules/browserstack-runner/lib/local.js:51:23)
    at /usr/local/lib/node_modules/browserstack-runner/lib/local.js:87:7
    at Object.cb [as oncomplete] (fs.js:168:19)
Uncaught undefined

/usr/local/lib/node_modules/browserstack-runner/node_modules/long-stack-traces/lib/long-stack-traces.js:80
                    throw ""; // TODO: throw the original error, or undefined?
                    ^
```

That last part seems like an issue in the `long-stack-traces` module, which isn't very useful. Thought at least there are multiple references to locations within this tool itself, which should help. I'm not familiar with that part of the codebase though.

**Comment by jzaefferer** [comment]
I'm not getting this error anymore. Since I have no idea what was causing it, it might or might not reappear in the future. Let's hope it doesn't.
