### ISSUE TITLE
Mach-O x86_64 tunnel binary appears to be totally busted

### ISSUE THREAD

**Issue by KJTsanaktsidis** [browserstack/browserstack-runner#124]
The browserstack tunnel binary for my Mac decided to stop working today, making karma freak out with `EACCESS`. This seems to work fine on our Linux CI box still. Looks like the Mac tunnel binary has become corrupted.

````
$ uname -a
Darwin kjs-macbook-pro.localdomain 14.4.0 Darwin Kernel Version 14.4.0: Thu May 28 11:35:04 PDT 2015; root:xnu-2782.30.5~1/RELEASE_X86_64 x86_64

$ karma start --single-run --reporters junit,progress --browsers bs_win81_chrome
28 07 2015 21:55:15.680:INFO [karma]: Karma v0.13.3 server started at http://localhost:9876/
28 07 2015 21:55:15.687:WARN [launcher]: Can not load "bs_win81_chrome"!
  Error: spawn EACCES
    at exports._errnoException (util.js:746:11)
    at ChildProcess.spawn (child_process.js:1162:11)
    at exports.spawn (child_process.js:995:9)
    at BrowserStackTunnel._startTunnel (/Users/kj/dev-environment/web-client/node_modules/karma-browserstack-launcher/node_modules/browserstacktunnel-wrapper/src/BrowserStackTunnel.js:144:19)
    at BrowserStackTunnel.startTunnel (/Users/kj/dev-environment/web-client/node_modules/karma-browserstack-launcher/node_modules/browserstacktunnel-wrapper/src/BrowserStackTunnel.js:161:12)
    at BrowserStackTunnel.start (/Users/kj/dev-environment/web-client/node_modules/karma-browserstack-launcher/node_modules/browserstacktunnel-wrapper/src/BrowserStackTunnel.js:170:12)
    at createBrowserStackTunnel (/Users/kj/dev-environment/web-client/node_modules/karma-browserstack-launcher/index.js:32:10)
    at Array.invoke (/usr/local/lib/node_modules/karma/node_modules/di/lib/injector.js:75:15)
    at get (/usr/local/lib/node_modules/karma/node_modules/di/lib/injector.js:48:43)
    at get (/usr/local/lib/node_modules/karma/node_modules/di/lib/injector.js:54:19)
    at get (/usr/local/lib/node_modules/karma/node_modules/di/lib/injector.js:54:19)
    at /usr/local/lib/node_modules/karma/node_modules/di/lib/injector.js:71:14
    at Array.map (native)
    at invoke (/usr/local/lib/node_modules/karma/node_modules/di/lib/injector.js:70:31)
    at Array.instantiate (/usr/local/lib/node_modules/karma/node_modules/di/lib/injector.js:59:20)
    at get (/usr/local/lib/node_modules/karma/node_modules/di/lib/injector.js:48:43)

$ chmod +x /Users/kj/dev-environment/web-client/node_modules/karma-browserstack-launcher/node_modules/browserstacktunnel-wrapper/bin/darwin/x64/BrowserStackLocal

$ karma start --single-run --reporters junit,progress --browsers bs_win81_chrome
29 07 2015 10:36:03.521:INFO [karma]: Karma v0.13.3 server started at http://localhost:9876/
29 07 2015 10:36:03.539:INFO [launcher]: Starting browser chrome 40.0 (Windows 8.1) on BrowserStack
29 07 2015 10:36:03.542:ERROR [launcher.browserstack]: Can not establish the tunnel.
Error: child failed to start:

$ /Users/kj/dev-environment/web-client/node_modules/karma-browserstack-launcher/node_modules/browserstacktunnel-wrapper/bin/darwin/x64/BrowserStackLocal
Killed: 9

$ sudo dtruss -f bash -c /Users/kj/dev-environment/web-client/node_modules/karma-browserstack-launcher/node_modules/browserstacktunnel-wrapper/bin/darwin/x64/BrowserStackLocal 2>&1 | tail
 3914/0xf8b0:  getrlimit(0x1007, 0x7FFF52B2A810, 0x7FFF52B2A840)		 = 0 0
 3914/0xf8b0:  sigprocmask(0x1, 0x0, 0x7FFF52B2A880)		 = 0x0 0
 3914/0xf8b0:  sigaltstack(0x0, 0x7FFF52B2A870, 0x7FFF52B2A880)		 = 0 0
 3914/0xf8b0:  getpeername(0x0, 0x7FFF52B2A868, 0x7FFF52B2A864)		 = -1 Err#38
 3914/0xf8b0:  sigprocmask(0x1, 0x0, 0x7FFF52B2A834)		 = 0x0 0
 3914/0xf8b0:  sigaction(0x2, 0x7FFF52B2A368, 0x7FFF52B2A390)		 = 0 0
 3914/0xf8b0:  sigaction(0x3, 0x7FFF52B2A368, 0x7FFF52B2A390)		 = 0 0
 3914/0xf8b0:  sigaction(0x14, 0x7FFF52B2A368, 0x7FFF52B2A390)		 = 0 0
 3914/0xf8b0:  execve("/Users/kj/dev-environment/web-client/node_modules/karma-browserstack-launcher/node_modules/browserstacktunnel-wrapper/bin/darwin/x64/BrowserStackLocal\0", 0x7FBC99C092E0, 0x7FBC99C08540)		 = -1 Err#13

$ file /Users/kj/dev-environment/web-client/node_modules/karma-browserstack-launcher/node_modules/browserstacktunnel-wrapper/bin/darwin/x64/BrowserStackLocal
/Users/kj/dev-environment/web-client/node_modules/karma-browserstack-launcher/node_modules/browserstacktunnel-wrapper/bin/darwin/x64/BrowserStackLocal: Mac-O 64-bit executable x86_64

$ strings /Users/kj/dev-environment/web-client/node_modules/karma-browserstack-launcher/node_modules/browserstacktunnel-wrapper/bin/darwin/x64/BrowserStackLocal
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/strings: object: /Users/kj/dev-environment/web-client/node_modules/karma-browserstack-launcher/node_modules/browserstacktunnel-wrapper/bin/darwin/x64/BrowserStackLocal truncated or malformed object (LC_SEGMENT_64 command 3 fileoff field plus filesize field extends past the end of the file)

$ otool -tV /Users/kj/dev-environment/web-client/node_modules/karma-browserstack-launcher/node_modules/browserstacktunnel-wrapper/bin/darwin/x64/BrowserStackLocal
/Users/kj/dev-environment/web-client/node_modules/karma-browserstack-launcher/node_modules/browserstacktunnel-wrapper/bin/darwin/x64/BrowserStackLocal:
string table extends past end of file
(__TEXT,__text) section
0000000100001240	pushq	$0x0
0000000100001242	movq	%rsp, %rbp
0000000100001245	andq	$-0x10, %rsp
0000000100001249	movq	0x8(%rbp), %rdi
000000010000124d	leaq	0x10(%rbp), %rsi
0000000100001251	movl	%edi, %edx
0000000100001253	addl	$0x1, %edx
````

**Comment by slashgrin** [comment]
+1 this affects me, too. :smile_cat:

**Comment by vedharish** [comment]
Hi @KJTsanaktsidis, is this related to `browserstack-runner`?
Looks like you're using [karma](https://github.com/karma-runner/karma) and [karma-browserstack-launcher](https://github.com/karma-runner/karma-browserstack-launcher) to run the tests.

[karma-browserstack-launcher Pull Request#31](https://github.com/karma-runner/karma-browserstack-launcher/pull/31) should resolve this issue.

**Comment by KJTsanaktsidis** [comment]
Sorry, don't know where I got the idea that this was the right issue to post in. Thanks!
