### ISSUE TITLE
All failing with "TypeError: worker.getTestBrowserInfo is not a function"

### ISSUE THREAD

**Issue by MrSwitch** [browserstack/browserstack-runner#141]
Please see this from Travis https://travis-ci.org/MrSwitch/hello.js/builds/90780396#L460

```text
Launching 6 worker(s) for 6 run(s).
/home/travis/build/MrSwitch/hello.js/node_modules/browserstack-runner/lib/server.js:240
Passed:') + ' %d tests, %d passed, %d failed; ran for %dms', worker.getTestBro
                                                                    ^
TypeError: Object #<Object> has no method 'getTestBrowserInfo'
    at reportHandler (/home/travis/build/MrSwitch/hello.js/node_modules/browserstack-runner/lib/server.js:240:140)
    at IncomingMessage.<anonymous> (/home/travis/build/MrSwitch/hello.js/node_modules/browserstack-runner/lib/server.js:306:46)
    at IncomingMessage.emit (events.js:92:17)
    at _stream_readable.js:944:16
    at process._tickCallback (node.js:448:13)
```

This also occurs when i run this locally too. It was working earlier today.

**Comment by MrSwitch** [comment]
Seems to have resolved itself https://travis-ci.org/MrSwitch/hello.js/builds/90780396
