### ISSUE TITLE
Samsung Galaxy Note 4 gets "Validation Failed - `device` invalid"

### ISSUE THREAD

**Issue by Krinkle** [browserstack/browserstack-runner#245]
## Expected Behavior

Test with Android 4.4.

## Actual Behavior

```
[android 4.4, Samsung Galaxy Note 4] Launching
Error from BrowserStack:  Error: Validation Failed - `device` invalid
    at IncomingMessage.<anonymous> (/qunit/node_modules/browserstack/lib/client.js:78:8)
    at IncomingMessage.emit (events.js:194:15)
    at endReadableNT (_stream_readable.js:1103:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

## browserstack.json
```json
  "browsers": [
    {
      "device": "Samsung Galaxy Note 4",
      "os": "android",
      "os_version": "4.4"
    },
```
```json
  "browsers": [
    {
      "device": "Galaxy Note 4",
      "os": "android",
      "os_version": "4.4"
    },
```

## Platform details
 
* browserstack-runner version: 0.9.
* node version: 10.x

## Details

It is listed at <https://www.browserstack.com/list-of-browsers-and-platforms/js_testing>
as `Galaxy Tab 4` `4.4`.

It is listed at <https://www.browserstack.com/automate/browsers.json>
as `Samsung Galaxy Tab 4` `4.4`.

```
nobody@3c338fbb8558:/qunit$ node
> bs=require('browserstack');
 client = bs.createClient({ username: process.env.BROWSERSTACK_USERNAME, password: process.env.BROWSERSTACK_KEY });
> client.getBrowsers(function (err, data) { console.log(err, data.filter(x => String(x.device).includes('Note'))); });

> null [ { …
  { os: 'android',
    os_version: '4.4',
    browser: 'Android Browser',
    device: 'Samsung Galaxy Note 4',
    browser_version: null,
    real_mobile: true },
```

**Comment by Krinkle** [comment]
I've tried other ones as well, but it seems they each have issues. Either a validation error, or a timeout after 2 minutes with the Automate dashboard saying "There was an error recording this video".

**Comment by Krinkle** [comment]
I've tried other ones as well, but it seems they each have issues. Either a validation error, or a timeout after 2 minutes with the Automate dashboard saying "There was an error recording this video".

* Samsung Galaxy Note 4: validation error.
* Samsung Galaxy S5: timeout, "There was an error recording this video".
* Samsung Galaxy Tab 4: validation error.
* Google Nexus 5: validation error.
