### ISSUE TITLE
Local binary for windows

### ISSUE THREAD

**Issue by dhimil** [browserstack/browserstack-runner#87]
Use exe for windows.

**Comment by bgaillard** [comment]
Hi, the current version does not work under Windows, here is the result of a run.
```
C:\workspace\myproject>browserstack-runner --verbose
Using config: C:\workspace\myproject\browserstack.json
Launching server on port: 8888
[Sat Jun 06 2015 00:12:56 GMT+0200 (Paris, Madrid (heure d'été))] Launching tunnel
Exception in thread "main" java.lang.NullPointerException
        at RSSh$MyLogger.log(Unknown Source)
        at RSSh.init(Unknown Source)
        at CommandLine.createNonAppletSsh(Unknown Source)
        at CommandLine.main(Unknown Source)

{ [Error: Command failed: C:\Windows\system32\cmd.exe /s /c "java -jar C:\workspace\myproject/BrowserStackTunnel.jar XXXXXXXX localhos
t,8888,0 -force -onlyAutomate"
Exception in thread "main" java.lang.NullPointerException
        at RSSh$MyLogger.log(Unknown Source)
        at RSSh.init(Unknown Source)
        at CommandLine.createNonAppletSsh(Unknown Source)
        at CommandLine.main(Unknown Source)
]
  killed: false,
  code: 1,
  signal: null,
  cmd: 'C:\\Windows\\system32\\cmd.exe /s /c "java -jar C:\\workspace\\myproject/BrowserStackTunnel.jar XXXXXXXX localhost,8888,0 -for
ce -onlyAutomate"' }
[Sat Jun 06 2015 00:12:59 GMT+0200 (Paris, Madrid (heure d'été))] Tunnel launching failed
***
 Setting the onlyAutomate parameter will stop local testing via command line from working with Live and Screenshots.
To enable local testing via the command line for Live and Screenshots, disconnect and reconnect the JAR without the -onlyAutomate parameter.
***
Verifying parameters
Starting local testing
null
Unable to re-connect
```

I think the following PR will solve several Windows problems https://github.com/browserstack/browserstack-runner/pull/101 (see also https://github.com/browserstack/browserstack-runner/issues/119).

**Comment by nakula** [comment]
this has been merged, sometime back
